comment:
  layout: "reach, diff, files, tree"
  behavior: default

coverage:
  status:
    project:
      default:
        informational: false   # ← показывать % покрытия
    patch:
      default:
        informational: true    # ← патч не ломает PR
