comment:
  behavior: default          # Всегда оставлять комментарий
  layout: "reach, diff, files, tree"
  require_changes: false     # Комментировать даже если diff = 0
  require_base: false
  require_head: false

coverage:
  status:
    project:                 # Показывать общий процент покрытия
      default:
        informational: true
    patch:                   # Показывать % для изменённых строк
      default:
        informational: true
