comment:
  layout: "reach, diff, files, tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false

coverage:
  status:
    project:                  # ← ВАЖНО: включает project coverage в PR
      default:
        informational: true
        threshold: null
    patch:
      default:
        informational: true
